export const availableResturant = [
  {
    id: 111191,
    primary_user: 968163,
    name: "Shawarma & Grill Station",
    description:
      "Restaurants serving Noodles, Shawarma, Burger, Chicken, Fried Chicken",
    vendor_group: "qsr",
    support_contact: "08039294997",
    support_email: "sharwamaandgrilsstation@gmail.com",
    logo_url:
      "https://files.chowdeck.com/images/2025/2025-07-04/9ths7KWFDNuqJ9tVCVhI2.PNG",
    cover_images: [
      {
        path: "https://files.chowdeck.com/images/2025/2025-06-16/MJUoiZifTzVe97riCC56A.PNG",
        original_filename: "",
      },
    ],
    slug: "shawarma-and-grill-station-abujautakowkm3l8",
    currency: "NGN",
    minimum_order_amount: 100000,
    is_active: true,
    is_open: false,
    current_domain: "live",
    offers_pickup: false,
    offers_delivery: false,
    vendor_type: "restaurant",
    registration_status:
      '{"basic_information":1,"operational_information":1,"menu_information":1,"bank_information":1,"incorporation_information":0,"signed_sla":0}',
    minimum_delivery_time: 33,
    maximum_delivery_time: 43,
    metadata: "{}",
    average_rating: "3.43",
    total_rating: 96,
    number_of_rating: 28,
    parent_vendor: null,
    flat_fee_per_item: 0,
    created_at: "2024-09-06T11:14:39.000Z",
    updated_at: "2025-07-05T17:02:06.000Z",
    likes: 42,
    available_hours: {
      default: {
        opening: "0830",
        closing: "1830",
      },
      Sunday: {
        opening: "0000",
        closing: "0000",
      },
    },
    notification_types: '["sms", "whatsapp"]',
    onboarded_by: 968163,
    location: "Jabi",
    vendor_class: "instant",
    charge_percent: "25.00",
    settlement_schedule: "T1",
    preorder_configuration: {},
    setting: '{"auto_accept_order":true}',
    service_charge_percent: "10.00",
    service_charge_cap: 250000,
    is_closed_by_operations: false,
    activation_status: "completed",
    reference: null,
    test_webhook_url: null,
    live_webhook_url: null,
    external_service_name: null,
    balance_threshold: null,
    category: "NEW RESTAURANT AUTO :robot_face:",
    secondary_support_contact: null,
    sla_url: null,
    has_pin: false,
    on_demand_settlement_schedule: "instant",
    risk_level: "low",
    is_soft_blocked: false,
    soft_block_reason: null,
    self_delivery: false,
    has_active_menu: true,
    first_order_date: "2024-09-19T08:51:51.000Z",
    chowpass_service_charge_percent: "2.50",
    chowpass_service_charge_cap: 90000,
    chowpass_tier: "agba",
    timezone: "Africa/Lagos",
    is_chowpass_vendor: true,
    coordinate: {
      x: 7.445472000000001,
      y: 9.0664001,
    },
    pretty_name: "69 A.E. Ekukinam St",
    city: "Utako",
    country: "Nigeria",
    distance: 13.8,
    rank: 52,
    custom_tag: "around_you",
    skip_discount_sorting: false,
    delivery_price: 280000,
    liked_by_customer: false,
    tags: ["chowsmart"],
    discounts: [],
    discount_text: "",
    should_sort: false,
    is_temporarily_unavailable: false,
    opening_time_text: "Opens on Monday at 8:30am",
    can_pre_order: false,
    current_is_open_state: false,
  },
  {
    id: 103394,
    primary_user: 226257,
    name: "Mjscookhouse",
    description: "Always a Finger Lickin Experience‼️",
    vendor_group: "ala",
    support_contact: " 0909 777 5308",
    support_email: "mjscookhouse@gmail.com",
    logo_url:
      "https://files.chowdeck.com/images/k4wbf2shheia22h8yv4d/1694716002.png",
    cover_images: [
      {
        path: "https://files.chowdeck.com/images/2024/2024-10-12/f8lvnluARMGhWs4Cg0DTL.png",
        original_filename: "",
      },
    ],
    slug: "mjscookhouse-gudueuw9st",
    currency: "NGN",
    minimum_order_amount: 100000,
    is_active: true,
    is_open: false,
    current_domain: "live",
    offers_pickup: true,
    offers_delivery: true,
    vendor_type: "restaurant",
    registration_status:
      '{"basic_information":1,"bank_information":1,"incorporation_information":0,"operational_information":1,"menu_information":1}',
    minimum_delivery_time: 46,
    maximum_delivery_time: 56,
    metadata:
      '{"agent_amount_per_order":5000,"only_start_delivery_after_marked_as_pickup":true}',
    average_rating: "4.03",
    total_rating: 387,
    number_of_rating: 96,
    parent_vendor: null,
    flat_fee_per_item: 0,
    created_at: "2023-09-09T03:44:09.000Z",
    updated_at: "2025-07-06T12:03:50.000Z",
    likes: 185,
    available_hours: {
      default: {
        opening: "0930",
        closing: "2015",
      },
      sunday: {
        opening: "1330",
        closing: "2030",
        day: "sunday",
        errors: null,
      },
      Sunday: {
        opening: "1330",
        closing: "2030",
      },
    },
    notification_types: '["sms", "whatsapp"]',
    onboarded_by: 226257,
    location: "Apo",
    vendor_class: "instant_preorder",
    charge_percent: "20.00",
    settlement_schedule: "T1",
    preorder_configuration: {
      cutoff_order_time: "0815",
      available_days: [
        "default",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
      ],
      menu_ready_time: "0910",
    },
    setting: '{"t3_agent_push_delay":5}',
    service_charge_percent: "10.00",
    service_charge_cap: 250000,
    is_closed_by_operations: false,
    activation_status: "completed",
    reference: null,
    test_webhook_url: null,
    live_webhook_url: null,
    external_service_name: null,
    balance_threshold: null,
    category: "T3 AGENT-MANAGED :selfie:",
    secondary_support_contact: null,
    sla_url: null,
    has_pin: false,
    on_demand_settlement_schedule: "instant",
    risk_level: "ultra-high",
    is_soft_blocked: false,
    soft_block_reason: null,
    self_delivery: false,
    has_active_menu: true,
    first_order_date: "2023-09-14T16:20:04.000Z",
    chowpass_service_charge_percent: "5.00",
    chowpass_service_charge_cap: 90000,
    chowpass_tier: "premium",
    timezone: "Africa/Lagos",
    is_chowpass_vendor: true,
    coordinate: {
      x: 7.484272799999999,
      y: 9.0051582,
    },
    pretty_name: "Donald Etiebet Close",
    city: "Gudu",
    country: "Nigeria",
    distance: 5.13,
    rank: 3,
    custom_tag: "handpicked",
    skip_discount_sorting: false,
    delivery_price: 100000,
    liked_by_customer: false,
    tags: [
      "Finger food",
      "Seafood ",
      "Breakfast",
      "Asian food ",
      "Caribbean food ",
      "Pastry ",
      "Rice",
      "Meat",
      "Italian food ",
      "Nigerian food ",
      "Fresh juice ",
      "Grills ",
      "African ",
    ],
    discounts: [],
    discount_text: "",
    should_sort: false,
    is_temporarily_unavailable: false,
    opening_time_text: "Opens tomorrow at 9:30am",
    can_pre_order: true,
    current_is_open_state: false,
  },
  {
    id: 120163,
    primary_user: 44967,
    name: "The Amala Hut",
    description: "Tasty Meals Always",
    vendor_group: "qsr",
    support_contact: "07063662275",
    support_email: "essien@chowdeck.com",
    logo_url:
      "https://files.chowdeck.com/images/2025/2025-06-05/xKZt0cGpRTM11aviFdqFG.jpeg",
    cover_images: [
      {
        path: "https://files.chowdeck.com/images/2025/2025-06-05/mrCMdYls8J67GhwGAj0K8.jpeg",
        original_filename: "",
      },
    ],
    slug: "d'tycoon-restaurantabuja6d2pv9",
    currency: "NGN",
    minimum_order_amount: 0,
    is_active: true,
    is_open: false,
    current_domain: "live",
    offers_pickup: false,
    offers_delivery: false,
    vendor_type: "restaurant",
    registration_status:
      '{"basic_information":1,"bank_information":1,"incorporation_information":0,"operational_information":1}',
    minimum_delivery_time: 7,
    maximum_delivery_time: 17,
    metadata: "{}",
    average_rating: "5.00",
    total_rating: 30,
    number_of_rating: 6,
    parent_vendor: null,
    flat_fee_per_item: 0,
    created_at: "2025-06-05T17:35:31.000Z",
    updated_at: "2025-07-05T07:26:20.000Z",
    likes: 7,
    available_hours: {
      default: {
        opening: "0900",
        closing: "1100",
      },
    },
    notification_types: '["sms", "whatsapp"]',
    onboarded_by: 44967,
    location: "Apo",
    vendor_class: "instant",
    charge_percent: "10.75",
    settlement_schedule: "T1",
    preorder_configuration: {},
    setting:
      '{"auto_accept_order":true,"auto_accept_delay_minutes":5,"auto_accept_prep_time":1,"auto_accept_notify_email":false,"t3_agent_push_delay":"","order_delayed_cancellation_enabled":true}',
    service_charge_percent: "10.00",
    service_charge_cap: 250000,
    is_closed_by_operations: false,
    activation_status: "completed",
    reference: null,
    test_webhook_url: null,
    live_webhook_url: null,
    external_service_name: null,
    balance_threshold: null,
    category: "NEW RESTAURANT AUTO :robot_face:",
    secondary_support_contact: null,
    sla_url: null,
    has_pin: false,
    on_demand_settlement_schedule: "instant",
    risk_level: "low",
    is_soft_blocked: false,
    soft_block_reason: null,
    self_delivery: false,
    has_active_menu: true,
    first_order_date: null,
    chowpass_service_charge_percent: null,
    chowpass_service_charge_cap: null,
    chowpass_tier: "free",
    timezone: "Africa/Lagos",
    is_chowpass_vendor: false,
    coordinate: {
      x: 7.5060085,
      y: 8.9785927,
    },
    pretty_name:
      "XGH4+CCJ, Rabo Madaki St, Abuja 900110, Federal Capital Territory, Nigeria",
    city: "Abuja",
    country: "Nigeria",
    distance: 0.69,
    rank: 7,
    custom_tag: "featured",
    skip_discount_sorting: false,
    delivery_price: 50000,
    liked_by_customer: false,
    tags: ["Nigerian food", "African food", "interconitinental", "jollof"],
    discounts: [],
    discount_text: "",
    should_sort: false,
    is_temporarily_unavailable: true,
    temporarily_unavailable_tag: "Unavailable",
    opening_time_text: "Opens on Sunday at 9:00am",
    can_pre_order: false,
    current_is_open_state: false,
  },
  {
    id: 107381,
    primary_user: 471698,
    name: "Domino's Pizza",
    description: "An amazing pizza ",
    vendor_group: "ala",
    support_contact: "09087629001",
    support_email: "apomall@dominos.ng",
    logo_url:
      "https://files.chowdeck.com/images/buaeojnwdak44l6wfvne/1704826059.png",
    cover_images: [
      {
        path: "https://files.chowdeck.com/images/2025/2025-06-13/wOB2uJNGFcHBUIHkp8m4u.jpg",
        original_filename: "",
      },
    ],
    slug: "dominos-pizza-wuseguduxtmzx6",
    currency: "NGN",
    minimum_order_amount: 100000,
    is_active: true,
    is_open: false,
    current_domain: "live",
    offers_pickup: false,
    offers_delivery: false,
    vendor_type: "restaurant",
    registration_status:
      '{"basic_information":1,"bank_information":1,"incorporation_information":0,"operational_information":1}',
    minimum_delivery_time: 37,
    maximum_delivery_time: 47,
    metadata: '{"only_start_delivery_after_marked_as_pickup":true}',
    average_rating: "3.31",
    total_rating: 129,
    number_of_rating: 39,
    parent_vendor: null,
    flat_fee_per_item: 0,
    created_at: "2024-03-23T12:08:03.000Z",
    updated_at: "2025-07-01T10:21:20.000Z",
    likes: 45,
    available_hours: {
      default: {
        opening: "0900",
        closing: "2300",
      },
      Thursday: {
        opening: "0900",
        closing: "2300",
      },
    },
    notification_types: '["sms", "whatsapp"]',
    onboarded_by: 30623,
    location: "Apo",
    vendor_class: "instant",
    charge_percent: "5.00",
    settlement_schedule: "T1",
    preorder_configuration: {},
    setting:
      '{"auto_accept_order":true,"auto_accept_notify_email":true,"auto_accept_delay_minutes":5,"max_delivery_distance":4}',
    service_charge_percent: "10.00",
    service_charge_cap: 250000,
    is_closed_by_operations: false,
    activation_status: "completed",
    reference: "dominosagungi",
    test_webhook_url: null,
    live_webhook_url: null,
    external_service_name: null,
    balance_threshold: null,
    category: "NEW RESTAURANT AUTO :robot_face:",
    secondary_support_contact: null,
    sla_url: null,
    has_pin: false,
    on_demand_settlement_schedule: "instant",
    risk_level: "low",
    is_soft_blocked: false,
    soft_block_reason: null,
    self_delivery: true,
    has_active_menu: true,
    first_order_date: "2024-03-25T16:22:40.000Z",
    chowpass_service_charge_percent: null,
    chowpass_service_charge_cap: null,
    chowpass_tier: "free",
    timezone: "Africa/Lagos",
    is_chowpass_vendor: false,
    coordinate: {
      x: 7.480713799999999,
      y: 9.003420599999998,
    },
    pretty_name:
      "Shop G014 - G018 Apo Mall, Along Murtala Mohammed Express Way, Gudu District, Ap Apo, Gudu, Bwari 901101, Federal Capital Territory, Nigeria",
    city: "Gudu",
    country: "Nigeria",
    distance: 4.64,
    rank: 31,
    custom_tag: "around_you",
    skip_discount_sorting: false,
    delivery_price: null,
    liked_by_customer: false,
    tags: ["Pizza "],
    discount_text: "Up to 4,550.00 off",
    should_sort: false,
    is_temporarily_unavailable: true,
    temporarily_unavailable_tag: "Unavailable",
    opening_time_text: "Opens on Sunday at 9:00am",
    can_pre_order: false,
    current_is_open_state: false,
  },
  {
    id: 121333,
    primary_user: 1570661,
    name: "Village Chief",
    description: "Restaurant",
    vendor_group: "ala",
    support_contact: "08169556599",
    support_email: "villagechiefgudu@gmail.com",
    logo_url:
      "https://files.chowdeck.com/images/cssafuqrtbcmwf9ni44p/1680862273.png",
    cover_images: [
      {
        path: "https://files.chowdeck.com/images/2024/2024-06-11/gPRBt4tUVeTX3kJiJG1Ey.png",
        original_filename: "",
      },
    ],
    slug: "village-chieflokogomapj2edj",
    currency: "NGN",
    minimum_order_amount: 100000,
    is_active: true,
    is_open: false,
    current_domain: "live",
    offers_pickup: false,
    offers_delivery: false,
    vendor_type: "restaurant",
    registration_status:
      '{"basic_information":1,"bank_information":1,"incorporation_information":0,"operational_information":1}',
    minimum_delivery_time: 47,
    maximum_delivery_time: 57,
    metadata: "{}",
    average_rating: "3.00",
    total_rating: 3,
    number_of_rating: 1,
    parent_vendor: null,
    flat_fee_per_item: 0,
    created_at: "2025-07-01T20:23:38.000Z",
    updated_at: "2025-07-05T13:02:17.000Z",
    likes: 2,
    available_hours: {
      default: {
        opening: "1100",
        closing: "2100",
      },
      sunday: {
        opening: "1100",
        closing: "1900",
        errors: null,
      },
      Sunday: {
        opening: "1100",
        closing: "1900",
      },
    },
    notification_types: '["sms", "whatsapp"]',
    onboarded_by: 44967,
    location: "Apo",
    vendor_class: "instant",
    charge_percent: "5.38",
    settlement_schedule: "T1",
    preorder_configuration: {},
    setting:
      '{"auto_accept_order":true,"auto_accept_delay_minutes":5,"auto_accept_prep_time":1,"auto_accept_notify_email":false,"t3_agent_push_delay":"","order_delayed_cancellation_enabled":true}',
    service_charge_percent: "10.00",
    service_charge_cap: 250000,
    is_closed_by_operations: false,
    activation_status: "completed",
    reference: null,
    test_webhook_url: null,
    live_webhook_url: null,
    external_service_name: null,
    balance_threshold: null,
    category: "T3 AGENT-MANAGED :selfie:",
    secondary_support_contact: null,
    sla_url: null,
    has_pin: false,
    on_demand_settlement_schedule: "instant",
    risk_level: "low",
    is_soft_blocked: false,
    soft_block_reason: null,
    self_delivery: false,
    has_active_menu: true,
    first_order_date: null,
    chowpass_service_charge_percent: null,
    chowpass_service_charge_cap: null,
    chowpass_tier: "free",
    timezone: "Africa/Lagos",
    is_chowpass_vendor: false,
    coordinate: {
      x: 7.470412700000002,
      y: 8.999539,
    },
    pretty_name:
      "XFXC+R57, Road, Lokogoma, Abuja 900110, Federal Capital Territory, Nigeria",
    city: "Lokogoma",
    country: "Nigeria",
    distance: 5.51,
    rank: 34,
    custom_tag: "around_you",
    skip_discount_sorting: false,
    delivery_price: 100000,
    liked_by_customer: false,
    tags: ["African"],
    discounts: [],
    discount_text: "",
    should_sort: false,
    is_temporarily_unavailable: true,
    temporarily_unavailable_tag: "Unavailable",
    opening_time_text: "Opens on Sunday at 11:00am",
    can_pre_order: false,
    current_is_open_state: false,
  },
].map((res) => ({
  id: res.id,
  name: res.name,
  cover_images: res.cover_images,
  average_rating: res.average_rating,
  tags: res.tags,
  opening_time_text: res.opening_time_text,
}));
